_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 9
                - 41
                - 55
                - 77
            "2":
                - 1
                - 9
                - 41
                - 55
                - 77
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.4
            "8":
                - 2
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 8
device:
    value: cuda
learning_rate:
    value: 0.0001
max_epochs:
    value: 100
model_name:
    value: Mmgnet
multi_rel_outputs:
    value: true
use_normal:
    value: false
use_rgb:
    value: false
